#!/usr/bin/env python3
"""Bake assets/lspd_badge.png into js/badge.js as a data: URI.

A 3D texture may NOT be loaded from a PNG next to index.html: under file://
Chrome treats a disk image as cross-origin and texImage2D throws (see
CLAUDE.md). The badge therefore ships base64-encoded inside a plain JS const,
which WebGL accepts from file:// as well.

The source is 1200x1600 with a transparent background; this trims it to the
alpha bbox and scales it down - the decal is a few centimetres wide on a bot's
chest, so 192 px of height is already more than the screen ever shows.

Run:  python3 tools/gen_badge.py
In:   assets/lspd_badge.png   Out: js/badge.js
"""

import base64, io, os

from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, 'assets', 'lspd_badge.png')
OUT = os.path.join(ROOT, 'js', 'badge.js')

HEIGHT = 192          # baked texture height in pixels

HEADER = """'use strict';
/* GENERATED by tools/gen_badge.py - do not edit by hand.
   assets/lspd_badge.png, trimmed to its alpha bbox and scaled to %d px tall,
   as a data: URI. A PNG read from disk taints WebGL under file://; a data URI
   does not (see CLAUDE.md -> Architektura). Used by TexGen.makeBotBadge(). */

"""


def main():
    im = Image.open(SRC).convert('RGBA')
    box = im.getbbox()          # transparent margin carries no information
    if box:
        im = im.crop(box)
    w = max(1, round(im.width * HEIGHT / im.height))
    im = im.resize((w, HEIGHT), Image.LANCZOS)
    buf = io.BytesIO()
    im.save(buf, 'PNG', optimize=True)
    b64 = base64.b64encode(buf.getvalue()).decode('ascii')

    with open(OUT, 'w') as f:
        f.write(HEADER % HEIGHT)
        f.write("const LSPD_BADGE_W = %d;\n" % w)
        f.write("const LSPD_BADGE_H = %d;\n" % HEIGHT)
        f.write("const LSPD_BADGE_PNG = 'data:image/png;base64,%s';\n" % b64)
    print('wrote %s (%d KB, %dx%d)' % (OUT, len(b64) // 1024, w, HEIGHT))


if __name__ == '__main__':
    main()
